### ISSUE TITLE
Missing stuff in com.subdigit.broker package

### ISSUE THREAD

**Issue by maxlam79** [subdigit/authentication#1]
HI subdigit,

Had git cloned the source code just to give it a try, it seems that the sources found on GitHub is missing of the package com.subdigit.broker. Perhaps you could enlighten me on this...

Cheers,
Max

**Comment by subdigit** [comment]
Well hi there, looks like all my GitHub notifications were being tucked away into a folder and I hadn't realized it did that with my own project issues as well.  So apologies for the really late and probably now irrelevant reply, but here it goes.

The broker package is available in this repository: https://github.com/subdigit/core
Pull the code from there as well and it should work.  I probably should have set this up as one repository, but in my eagerness and newness to GitHub, I split it all up thinking I'll have a bunch of these to combine together as needed.  Which is essentially how the Maven pull should work.

Either way, let me know if that at least solves the compilation issue for you.
